trigger:
- main
steps:
   - task: AzureFunctionAppContainer@1
     inputs:
       azureSubscription: 'DockerDevopsServiceCon'
       appName: 'fn-dev-devops-eastus-001'
       imageName: 'pipelines-javascript-docker'