trigger:
- master
jobs:
- job: Linux
  pool:
    name: devopsselfhosted    # your job runs on an agent in this pool
  steps:  
   - task: BuildandPushToContainer@1
     inputs:
      containerRegistry: 'dockcontainerregistry'
      repository: 'sn-acm-api-dev'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

   - task: SetAzureFunctionAppContainerRepo@1
     inputs:
       azureSubscription: 'DockerDevopsServiceCon'
       appName: 'fn-dev-devops-eastus-001'
       imageName: 'sn-acm-api-dev'